packages:
  - apps/*
  - packages/*
  - tests/load

sharedWorkspaceLockfile: true
linkWorkspacePackages: true
saveWorkspaceProtocol: rolling

overrides:
  'rpc-websockets@9.1.3>ws': 8.18.3

allowBuilds:
  '@reown/appkit': true
  bigint-buffer: true
  bufferutil: true
  cpu-features: true
  esbuild: true
  msgpackr-extract: true
  protobufjs: true
  sharp: true
  ssh2: true
  unrs-resolver: true
  utf-8-validate: true

minimumReleaseAgeExclude:
  - '@magicblock-labs/ephemeral-validator-darwin-arm64@0.13.20'
  - '@magicblock-labs/ephemeral-validator-darwin-x64@0.13.20'
  - '@magicblock-labs/ephemeral-validator-linux-arm64@0.13.20'
  - '@magicblock-labs/ephemeral-validator-linux-x64@0.13.20'
  - '@magicblock-labs/ephemeral-validator@0.13.20'
