packages:
  - apps/*
  - packages/*
  - tests/load

sharedWorkspaceLockfile: true
linkWorkspacePackages: true
saveWorkspaceProtocol: rolling

allowBuilds:
  bufferutil: true
  cpu-features: true
  esbuild: true
  msgpackr-extract: true
  protobufjs: true
  sharp: true
  ssh2: true
  unrs-resolver: true
  utf-8-validate: true
